In [26]:
import numpy as np

class SampleDictVectorizer:
    def __init__(self):
        self.feature_indices_ = {} 
        # Dictionary: for assigning features an index value which will be used as the index for our columns

        self.num_features_ = 0 
        # Our index values for our features will start at 0, also serves as the number of features


    def fit(self, data):

        for dictionary in data: 
        # Start by looping through our list of dictionaries

            for feature in dictionary.keys(): 
            # With the first dictionary, loop through the keys using the feature variable

                if feature not in self.feature_indices_: 
                # Taking the first key (feature), check if the key exists in our feature_indeces_ dictionary, if not then:


                    self.feature_indices_[feature] = self.num_features_ 
                    # Create an entry using the feature as the key and our num_features_ as its value


                    self.num_features_ += 1 
                    # For every loop add 1 to our num_features


    def transform(self, data):

        num_samples = len(data) 
        # Find the length of our list, this serves as the amount of rows

        X_sparse = np.zeros((num_samples, self.num_features_))
        # Create a 3x3 sparse matrix using numpys zeros function, with 3 rows (num_samples), and 3 columns (num_features_)

        for index, dictionary in enumerate(data):
        # Loop through our dictionary list taking the index and dictionary using the enumerate function

            for feature in dictionary.keys():
            # With the first dictionary, loop through the keys using the feature variable

                if feature in self.feature_indices_:
                #Verify that the feature exists in our feature_indices_ dictionary, then:

                    feature_index = self.feature_indices_[feature]
                    # Make feature_index equal to the features dictionary value 

                    X_sparse[index, feature_index] = 1
                    # Go to the row (index) and the column index (feature_index) and changed that value to 1



        return X_sparse
        #return sparse matrix

In [33]:

# Sample dictionary list
data = [
    {'color': 'orange', 'size': 'small'},
    {'color': 'white', 'model': 'v1.01'},
    {'color': 'green', 'year': '2023'}
]


In [34]:

# Create an instance of SampleDictVectorizer
vectorizer = SampleDictVectorizer()

# Fit the data
vectorizer.fit(data)

# Transform the data
X_sparse = vectorizer.transform(data)

# Print the matrix
print(X_sparse)

[[1. 1. 0. 0.]
 [1. 0. 1. 0.]
 [1. 0. 0. 1.]]
